contracts/interfaces/external/stargate/IStargateRouter.sol
Updates swapETH to swapETHAndCall, and introduces SwapAmount struct in StargateRouter interface.
Changed swapETH function to swapETHAndCall in IStargateRouter. This function now takes a new struct SwapAmount, which specifies the amount to be swapped and the minimum swap amount, and the LZ tx params, along with a payload to send to the destination, replacing individual parameters in the old swapETH function. Also added SwapAmount struct to IStargateRouterBase.
=> Rural Amethyst Tapir - All ETH can be stolen during rebalancing for mTOFTs that hold native #69

contracts/interfaces/external/stargate/IStargateRouter.sol
This PR introduces `IStargatePool` and `IStargateFactory` interfaces to `IStargateRouter`. `IStargatePool` includes methods to determine conversion rates and cliff durations for local and shared pools. `IStargateFactory` adds a method to retrieve specific pool addresses using the pool ID. This addition aligns with recent conventions and taps into the continuous efforts to modularize the Stargate system. To test this change, use contracts that interact with `IStargateRouter` and ensure they can now access and interact with pool conversion rates and share cliff durations, and retrieve specific pool addresses.
=> Rural Amethyst Tapir - Stargate Pools conversion rate leads to token accumulation inside the Balancer contract #71

contracts/interfaces/external/stargate/IStargateRouter.sol, contracts/tapiocaOmnichainEngine/TapiocaOmnichainReceiver.sol
Updated the arguments passed in function call in TapiocaOmnichainReceiver contract
In TapiocaOmnichainReceiver contract, the argument passed to the function `_internalRemoteTransferSendPacket` has been updated from `remoteTransferMsg_.owner` to `_srcChainSender`
=> Skinny Wool Mallard - Wrong parameter in remote transfer makes it possible to steal all USDO balance from users #111

contracts/Swapper/ZeroXSwapper.sol, contracts/interfaces/bar/ILeverageExecutor.sol
patch(`ZeroXSwapper`): refund dust to sender if `amountIn` was not used entirely [`86dth3q0e`]
- Check swapped amount and refund if dust is left in the contract
`GT_CU-86dth3q0e-zerox-swapper-refund`
=> deadrosez | [L-02] BaseLeverageExecutor does not verify that the actually swapped amount is the same as amountIn

contracts/interfaces/periph/IPearlmit.sol, contracts/pearlmit/Pearlmit.sol
fix(`Pearlmit`): Add `clearAllowance()` & resetting allowance on  `_afterTransferFrom()` [`86dtj597v`]
patch(`Pearlmit`): Rem unused param in `clearAllowance()` & updated `IPearlmit` with new `clearAllowance()` [`86dtj597v`]
=> Reset the allowance after a transfer and add external func to clear it explicitly

contracts/tapiocaOmnichainEngine/BaseTapiocaOmnichainEngine.sol, test/mocks/ToeTokenMock/ToeTokenMock.sol
fix(`BaseTOE`): Removed `transferFrom()` override to not use `Pearlmit` anymore [`86dtj04d9`]
=> Remove the `Pearlmit` code from `TOE::transferFrom()` `CU-86dtj04d9`

contracts/tapiocaOmnichainEngine/extension/TapiocaOmnichainExtExec.sol, test/Magnetar/Magnetar.t.sol
- sanitized `erc20PermitApproval` target
- sanitized `erc721PermitApproval` target
- sanitized `pearlmitApproval` target
- some tests fixes
=> 0xAdrii | [HIGH-01] - Tapioca omnichain extender flow allows performing delegatecalls to arbitrary addresses #1 [`CU-86dtjja7x`]

contracts/pearlmit/Pearlmit.sol
fix(`Pearlmit`): Removed double defined `__storeApproval()` [`86dtjkpj5`]
=> Carrotsmuggler | [L-01] __storeApproval differs from permitC in terms of expiry `CU-86dtjkpj5`

contracts/pearlmit/Pearlmit.sol
fix(`Pearlmit`): Calling `_clearAllowance()` with the right arg [`86dtjkuqg`]
=> [M-Pearlmit-01] `_afterTransferFrom` removes approval from wrong user `CU-86dtjkuqg`

contracts/oracle/utils/ChainlinkUtils.sol
patch(`ChainlinkUtils`): Made `DEFAULT_STALE_PERIOD` public + settable [`86dtjph9u`]
- `DEFAULT_STALE_PERIOD` is now public
- New `changeDefaultStalePeriod()`
=> make `DEFAULT_STALE_PERIOD` on `ChainlinkUtils` settable `CU-86dtjph9u`

contracts/Magnetar/Magnetar.sol, contracts/interfaces/periph/ITapiocaOmnichainEngine.sol, contracts/tapiocaOmnichainEngine/BaseTapiocaOmnichainEngine.sol, contracts/tapiocaOmnichainEngine/TapiocaOmnichainSender.sol
- New `BaseTOE::encode()` which uses the same `OFTMsgCodec` logic in addition to a `_from`
- Adapted `BaseTOE::_buildOFTMsgAndOptions()` take a new `_from` param
- Adapted `BaseTOE::quoteSendPacket()` to use `_buildOFTMsgAndOptions()`
- Adapted `TOESender::sendPacket()` to use `_buildOFTMsgAndOptions()`
- New `TOESender::sendPacketFrom()`
=> 0xAdrii | [H-06] - Compose messages will wrongly hardcode source chain sender as Magnetar `CU-86dtb8rra`

contracts/Cluster/Cluster.sol, contracts/Magnetar/Magnetar.sol, contracts/Magnetar/modules/MagnetarBaseModule.sol, contracts/Magnetar/modules/MagnetarMintModule.sol, contracts/Magnetar/modules/MagnetarOptionModule.sol, contracts/interfaces/periph/ICluster.sol, contracts/interfaces/periph/IPearlmit.sol, contracts/pearlmit/Pearlmit.sol, contracts/pearlmit/PearlmitHandler.sol, contracts/pearlmit/PearlmitHash.sol, contracts/tapiocaOmnichainEngine/TapiocaOmnichainSender.sol, test/Magnetar/Magnetar.t.sol, test/Magnetar/modules/MagnetarTestHelper.sol, test/pearlmit/Pearlmit.t.sol, test/pearlmit/PearlmitBase.t.sol, test/toe/ToeToken.t.sol
patch(`Pearlmit`): Removed unnecessary `_afterTransferFrom` [`86dtm14xr`]
chore(`gitmodule`): `PermitC` checkout to `main` [`86dtkznra`]
patch(`Pearlmit`): Adapted to `PermitC` changes [`86dtkznra`]
patch(`Magnetar`): Adapted `Magnetar` + `modules` to `Pearlmit` changes [`86dtkznra`]
chore(`gitmodule`): `PermitC` checkout to `main` [`86dtkznra`]
patch(`Magnetar`): Fix stack too deep on `_processExerciseOption()` [`86dtm2tgr`]
patch(`Cluster`): Removed `target` in `hasRole` [`86dtm14xr`]
patch(`PearlmitHash`): Updated `TYPEHASH` [`86dtm14xr`]
patch(`PearlmitTest`): Add `test_hashBatchTransferFrom` [`86dtm14xr`]
fix(`PearlmitHash | IPearlmit`): Inconsistencies between `TYPEHASH` and `PermitBatchTransferFrom` [`86dtm14xr`]
chore(`test`): Adapted tests to `IPearlmit` change  [`86dtm14xr`] …
=> Pearlmit post PermitC change update `CU-86dtm14xr`

contracts/pearlmit/Pearlmit.sol
patch(`Pearlmit`): Cleaned compile errors [`86dtm2tgr`]
=> Clean compile warnings on `Pearlmit` `CU-86dtm2tgr`

contracts/interfaces/bar/IBigBang.sol
patch(`IBigBang`): Adapted `openInterestDebt` related calls [`86dtm99eu`]
=> C4#120 0xadrii - Not properly tracking debt accrual `CU-86dtm99eu`

contracts/Magnetar/MagnetarStorage.sol
chore(`MagnetarStorage`): Removed unused `MAGNETAR_ACTION` constants [`86dtn6486`]
=> Remove unused MagnetarStorage old actions IDs `CU-86dtn6486`

contracts/Magnetar/Magnetar.sol
fix(`Magnetar`): Wrong param decoding on `TOE::sendPacketFrom()` [`86dtnmw0q`]
=> Mangnetar _processOFTOperation bugfix `CU-86dtnmw0q`

contracts/tapiocaOmnichainEngine/BaseTapiocaOmnichainEngine.sol, contracts/tapiocaOmnichainEngine/TapiocaOmnichainSender.sol
patch(`BaseTOE`): Removed `_from` re assignment in `encode()` [`86dtnqedc`]
patch(`TOESender`): Updated `sendPacket()` and `sendPacketFrom` [`86dtnqedc`]
- Follow up to `BaseTOE::encode()` change,  `sendPacket` will use `_from` in `_buildOFTMsgAndOptions` instead of `address(0)`
-`sendPacketFrom()` will revert if `address(0)` is passed in `_from`
- `sendPacketFrom()` will debit `_from` instead of `msg.sender`
=> Update `sendPacketFrom` logic on `BaseTOE` `CU-86dtnqedc`

contracts/Magnetar/Magnetar.sol, test/Magnetar/Magnetar.t.sol, test/Magnetar/modules/MagnetarTestHelper.sol
feat(`Magnetar`): Add `_magnetarHelper` to constructor args [`86dtqewp7`]
chore: Adapted tests to latest changes [`86dtqewp7`]
=> Add MagnetarHelper address on constructor arg in Magnetar `CU-86dtqewp7`

contracts/Magnetar/MagnetarHelper.sol, contracts/Magnetar/modules/MagnetarBaseModule.sol, contracts/interfaces/periph/IMagnetarHelper.sol
feat(`MagnetarHelper`): Add `roundUp` param to `getAmountForBorrowPart()` & `getBorrowPartForAmount()` [`86dtqt272`]
patch(`MagnetarBaseModule`): Updated `_marketRepay()` to use rounding on `MagnetarHelper` conversion [`86dtqt272`]
=> Update MagnetarHelper conversion functions to include rounding parameter `CU-86dtqt272`

contracts/Magnetar/BaseMagnetar.sol, contracts/Magnetar/Magnetar.sol, contracts/interfaces/periph/ICluster.sol, contracts/tapiocaOmnichainEngine/TapiocaOmnichainEngineCodec.sol, contracts/tapiocaOmnichainEngine/TapiocaOmnichainReceiver.sol, contracts/tapiocaOmnichainEngine/TapiocaOmnichainSender.sol
- `TOEReceiver` : `_lzReceive` will send the whole message instead of just the composed one to  `lzCompose`
- `TOESender`: `sendPacket` & `sendPacketFrom` will now return `message` and `options`
=> Fix lzCompose msg reception and toe codec `CU-86dtr19vp`

contracts/oracle/implementation/Arbitrum/TapOptionOracle.sol
patch(`TapOptionOracle`): Removed `onlyRole(DEFAULT_ADMIN_ROLE)` check on `get()` [`86dttqguv`]
=> Remove role check on TAP OPTION ORACLE get `CU-86dttqguv`

contracts/Magnetar/modules/MagnetarOptionModule.sol, contracts/interfaces/periph/IMagnetar.sol, test/Magnetar/modules/MagnetarOptionModule.t.sol
patch(`MagnetarOptionModule`): Updated `LockAndParticipateData` struct + adapted consumer funcs [`86dtv19ar`]
=> Update Magnetar LockAndParticipateData to pass in tOLP ID + YB `CU-86dtv19ar`
